language: python

python:
  - 3.6

dist: xenial

# Update pip to the latest version
before_install:
  - python --version
  - pip install -U pip

install:
  - pip3 install -r requirements.txt

script:
  - python -m unittest tests/reader_tests.py

deploy:
  provider: pypi
  username: "__token__"
  password: "$PYPI_TOKEN"
  on:
    branch: main