language: python
python:
  - 3.6

dist: bionic

# Update pip to the latest version
before_install:
  - python --version
  - pip install -U pip

install:
  - pip install -r requirements.txt

script:
  - python -m unittest tests/reader_tests.py

before_deploy:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      python3 -m venv ~/venv;
      source ~/venv/bin/activate;
    fi

deploy:
  provider: pypi
  username: "__token__"
  password: "$PYPI_TOKEN"
  on:
    branch: main